# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 154268a49d9a1e31af0b608a86178099844b2d30f0e0abaa7adb88d87410267725acc97f174603382433a5a43b049b87b8e3866dd2c9ba8d7c81e420d2208f20

test:
  secret_key_base: 14b2740e808aa8f3d0f10569e7c4d1d3a1c0d134b8664fa6171bca13fa93454af079f5d9a10749b17bf36ac593c659263d8aafaefc562bef77c74d51b8880d06

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
